Ajv8 upgrade
fastify/fast-json-stringify pull request #353
Opened 2021-08-24 14:33 UTC by Eomm

This PR update the `ajv` dependency from v6 to v8

The main changes are:

- ajv now does not ignore duplicated `$id` in inline schemas* => for this reason I have to add a `delete` statement. we should test this branch within Fasfity
- ajv does not include `ajv-formats` by default, I have added it

## Todos

- [ ] align next branch
- [ ] it must be tested within Fastify

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-08-24 16:21 UTC, mcollina requested changes
I think there are a lot of spurious changes here

2021-08-24 16:21 UTC, mcollina commented on package.json
> +  "version": "2.7.8",
why this change?

2021-08-25 07:12 UTC, Eomm commented
I'm must align `next` to `master` first

2021-08-25 10:23 UTC, Eomm commented
Ready to review

Tested with Fastify next here: https://github.com/fastify/fastify/actions/runs/1166101438 all green 🟢

2021-08-25 13:23 UTC, mcollina approved these changes
lgtm

2021-08-25 13:24 UTC, merged