refactor: move global variables into class context
fastify/fast-json-stringify pull request #527
Opened 2022-09-07 14:15 UTC by ivan-tymoshenko

Through the building serializer process, different function use the same context that is stored in global. I think it would be better to share this context using the class.

Also, I separated the `build` function call into two different calls: 
1. Class constructor initiates all context variables, including external schemas.
2. The `build` method: should build the schema serializer.
You can't call the `build` method of the SerializerFactory with different schemas yet. I want to add this functionality, but in another PR.

The API of the library is still the same.

2022-09-07 16:08 UTC, mcollina approved these changes
lgtm

2022-09-07 16:44 UTC, climba03003 requested changes

2022-09-07 16:44 UTC, climba03003 commented on serializer.js
> +      default:
I would split this changes to another PR.

2022-09-07 16:55 UTC, climba03003 commented on serializer.js
> +      default:
Nevermind, I see where it comes from.

2022-09-07 16:55 UTC, climba03003 approved these changes
LGTM.

2022-09-19 06:51 UTC, mcollina commented
Can you rebase? This now conflicts.

2022-11-06 12:07 UTC, closed without merging