optimize enums with a single value
fastify/fast-json-stringify pull request #663
Opened 2023-11-11 20:35 UTC by bmeck

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] <s>documentation is changed or added</s>
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-11-11 21:38 UTC, mcollina approved these changes
lgtm

Good spot!

2023-11-11 21:43 UTC, ivan-tymoshenko requested changes
This will create a difference between the logic of: enum with one value and enum with multiple values. You need to check that data value is equal to schema one before inserting it.

2023-11-11 21:46 UTC, ivan-tymoshenko commented
You can read this thread for more details.
https://github.com/fastify/fast-json-stringify/discussions/532#discussioncomment-3781347

2023-11-11 22:01 UTC, bmeck commented
@ivan-tymoshenko this seems a bit odd since you don't do similar checks for things like `const`, is there a clear difference here with `const`? I'm not sure how to sanely validate against a single value at a glance in the code here. `lib/schema-validator` doesn't seem to have a clear way to check against a deep property. I'm fine with this staying blocked however since I was just driving by and was surprised at a massive sudden drop in speed on me poking with different schemas.

2023-11-11 22:11 UTC, ivan-tymoshenko commented
The problem is how the serialization function would behave in case when it receives a value that is not in the enum.

1.
```js
const schema = { type: 'string', enum: ['foo', 'bar'] }
const serialize = fjs(schema)
serialize('baz') // should return baz IIRC
```

2. 
```js
const schema = { type: 'string', enum: ['foo'] }
const serialize = fjs(schema)
serialize('baz') // will return 'foo'
```

IMO this is confusing. I agree that situation with `const` looks very close. Unfortunatelly this library doesn't have a crear answer to this question. You can read the thread I sent you. It's exactly about this problem.

You still will have some performance boost if you add a sanity check.

2023-11-11 22:16 UTC, ivan-tymoshenko commented
My few recomendations on adding enum support:
- I would add them for strings only
- if received value is in an enum, it should insert value, if value is not in the enum it should sanitize received string (default bahaviour)

This will give you the performance boost, because you will avoid the string sanitizing in a hot path.

2023-11-11 22:18 UTC, bmeck commented
@ivan-tymoshenko I did read that thread but it didn't enlighten me; per https://json-schema.org/draft/2020-12/json-schema-validation#section-6.1.3

> [6.1.3. ](https://json-schema.org/draft/2020-12/json-schema-validation#section-6.1.3)[const](https://json-schema.org/draft/2020-12/json-schema-validation#name-const)
The value of this keyword MAY be of any type, including null.

> Use of this keyword is functionally equivalent to an ["enum"](https://json-schema.org/draft/2020-12/json-schema-validation#enum) ([Section 6.1.2](https://json-schema.org/draft/2020-12/json-schema-validation#enum)) with a single value.

2023-11-11 22:19 UTC, ivan-tymoshenko commented
Can you tell me what this library should do if it receives a value that is not in the enum?

2023-11-12 03:21 UTC, bmeck commented
@ivan-tymoshenko Per the specification, having a value outside of the single value of the enum means that the value passed in isn't valid and is seemingly subject to the README:

> While the schema is currently validated for any developer errors, there is no guarantee that supplying user-generated schema could not expose your application to remote attacks.

> Users are responsible for sending trusted data. fast-json-stringify guarantees that you will get a valid output only if your input matches the schema or can be coerced to the schema. If your input doesn't match the schema, you will get undefined behavior.

Additionally from that thread linked:

> fast-json-stringify guarantees that you will get a valid output only if your input matches the schema or can be coerced to the schema. If your input doesn't match the schema, you will get undefined behavior.

So sending values outside of those explicit values (including `null`) would be invalid per the schema provided. So the suggestion above of:

> if received value is in an enum, it should insert it, if value is not in the enum it should sanitize received string (default bahaviour)

Would actually produce an invalid value for the schema and should not be done.

Since these are values are outside of valid values for the schema it seems likely to be up to implementer desires according to the README and thread linked; I don't think checking the value is needed given these points existing.

I'm not a maintainer so it is hard to say what is desired by maintainers, but that the spec call out of equivalence isn't valid here is surprising. My only comment is that likely `const` and single value `enum` should properly align. Personally, I'd rather expect every value outside of the schema to simply be allowed undefined behavior. The README however does list a few cases where things are explicitly validated and thrown and I'm less clear on motivations for those so once again I would struggle to say when things should be checked. Having only `enum` check while `const` does not invalidates none of the README guarantees.

Calling out an validating enums is certainly possible to hot path outside of single values with some steps like you suggest above but seems out of my general cause of making this PR which was one of surprise.

2026-09-06 13:17 UTC, Tony133 commented
Closing this PR as it has been inactive for some time and may no longer be aligned with the current state of the codebase.

If the changes are still relevant, feel free to open a new PR with the necessary updates.

2026-09-06 13:17 UTC, closed without merging