stream stringify (DRAFT)
fastify/fast-json-stringify pull request #709
Opened 2024-04-12 12:55 UTC by cesco69

DO NOT MERGE! THIS IS A WORKING IN PROGRESS!

I don't know if this idea has ever been discussed or if it can actually be a performance improvement.
The idea is to implement a stringify version that write a Readable to consume in the server response during the stringify process
e.g:
```
res.type('json');
var stream = new Readable()
res.send(stream);
stringify(response, stream);
```

2024-04-12 14:53 UTC, mcollina commented
I don't this would yield any significant performance improvement.

2024-04-12 15:05 UTC, cesco69 commented
> I don't this would yield any significant performance improvement.

@mcollina this will be complicated to test

2024-04-12 21:32 UTC, ivan-tymoshenko commented
I think this might give you the perf boost only if you have a  really large array in the response. So I would try to make a chunk at least per object and not per object key/value. Making chunks small will give you a big overhead.

2024-04-12 21:36 UTC, ivan-tymoshenko commented
Simple math. If time required to send one tcp package from server to client is more than time for serializing the whole response than it doesn't make a lot of sense. If I understand the idea correctly.

2024-04-15 10:50 UTC, mcollina requested changes
This _will be slower_ than before, because it generates all data synchronously before beginning to write it. Note you'll still generate all the content synchronously and queue it in the stream. Let's say this queuing cost 1ns. If you enqueue 1 chunk, it would take 1 ns. If you enqueue 1000 chunks, it would cost 1ms. Given that you already have 100% of the data to be sent, it's not worth the complexity.

Streams are great if we could start sending some of the data while waiting for some other I/O to happen. This reduces loading time etc. But not in this case.

2024-04-15 11:47 UTC, cesco69 commented
@mcollina 
> Streams are great if we could start sending some of the data while waiting for some other I/O to happen. This reduces loading time etc. But not in this case.

Why not?
```ts
  const stream = new Readable()
  stream.pipe(res);
  stringify(data, stream);
```
`stringify` write on stream each chunk oj json and `stream.pipe(res);` send each to client

2024-04-15 12:10 UTC, mcollina commented
It doesn't. You are generating all the chunks synchronously and enqueuing them. After all of that is completed, the event loop will pick up and do all the work to send them through (I'm simplifying).

2024-04-15 12:27 UTC, cesco69 commented
> It doesn't. You are generating all the chunks synchronously and enqueuing them. After all of that is completed, the event loop will pick up and do all the work to send them through (I'm simplifying).

I have tried , it's true ! I think I need to study how streams work

:(

2024-04-15 12:31 UTC, closed without merging