fix: merged schemas cache key
fastify/fast-json-stringify pull request #729
Opened 2024-06-26 14:35 UTC by DamienVicet

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] ~~documentation is changed or added~~
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Hello, this PR fixes #724.

When diving in the bug, I found that the `context.mergedSchemasIds` Map, added by @ivan-tymoshenko, is using objects as keys. This caused the schema to infinitely try to build and results into `Maximum call stack size exceeded` error.
So I replaced the key by a hash of the object, then I got another problem : `anyOf inside allOf` test failed because, to my understanding, we try to cache different merged schemas using the same key in `context.mergedSchemasIds` (like merged schemas from `buildOneOf` and from `buildAllOf` functions).

I am not sure of the solution. Thank you for your review !

2024-06-26 14:47 UTC, gurgunday reviewed
This should work, i don't know about the performance of that package, but this could be a lot faster to set unique identifiers:

```js
const idMap = new WeakMap();
const getId = (obj) => {
  if (!idMap.has(obj)) {
    idMap.set(obj, Symbol('id'));
  }
  return idMap.get(obj);
};

const id = getId(object);
```

2024-06-26 14:50 UTC, gurgunday approved these changes
lgtm

2024-07-01 14:20 UTC, mcollina approved these changes
lgtm

I'm a bit scared of this as it would likely increase our build/startup time.

2024-07-01 14:25 UTC, ivan-tymoshenko requested changes
thank you for your PR. I'm rejecting it for now, because I remember I was using the objects pointers as keys on purpose to compare objects when going through the refs cycles. I need a bit more time to look at this PR. I will try to review asap.

2024-07-02 22:33 UTC, ivan-tymoshenko commented
I found the problem. I'm working on the solution. Unfortunatelly merging schemas with recurcive references is the most complecated part of this library and take tons of time every time when we need to fix the bug.

2025-02-14 22:20 UTC, grreeenn commented
hi @ivan-tymoshenko , any progress on this? Can I maybe try to take it from wherever you've got to?

2026-09-06 13:19 UTC, Tony133 commented
Closing this PR as it has been inactive for some time and may no longer be aligned with the current state of the codebase.

If the changes are still relevant, feel free to open a new PR with the necessary updates.

2026-09-06 13:19 UTC, closed without merging